apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: stefanvopipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: stefanvopipelinesjavascriptdocker 
    spec:
      containers:
        - name: stefanvopipelinesjavascriptdocker 
          image: svacrtest.azurecr.io/stefanvopipelinesjavascriptdocker
          ports:
          - containerPort: 8080